### ISSUE TITLE
harj. wk4-30 tehtävä / materiaali  kaipaa tarkennusta (hetu?)

### ISSUE THREAD

**Issue by aa-m-sa** [web-selainohjelmointi/web-selainohjelmointi.github.io#40]
Edeltävä materiaali ei esittele mitään regex-pattern / minlength -validaattoreita syvällisempää, mutta spesifikaation mukainen hetu ei ole ihan regexillä validoitavissa.

Jos hetulle riittää regex-tarkistus onko muotoa (ddddddydddw), sen voisi sanoa, tai sitten kaivattaisiin mainintaa että pitää kehitellä appiin (?) jokin validaattorifunktio.

(wl;dr: exercise 30 would benefit from a more precise problem statement)

**Comment by avihavai** [comment]
Tämä menee ainakin sen "Lisää lomakkeista ja niiden validoinneista"-linkin takana olevan sivun Custom Validation -kohdan avulla. Jos epäilet, että osallistujat eivät käy katsomassa linkin takaa, tee PR :).

**Comment by aa-m-sa** [comment]
No en minä ainakaan huomannut että "lisälukemista" takana olisi vaadittua infoa tehtävän suorittamiseen -> PR #41
