### ISSUE TITLE
Viikko 6, Tehtävä 45: Elokuvien haku: OMDb API (2p), materiaalissa vanhentunutta tietoa

### ISSUE THREAD

**Issue by mknn** [web-selainohjelmointi/web-selainohjelmointi.github.io#42]
Viikko 6, Tehtävä 45: Elokuvien haku: OMDb API (2p), tehtäväohjeistuksessa ohjeistetaan poistamaan otsake "X-Requested-With" AJAX-pyynnöistä. Otsake on kuitenkin jo poistettu käytöstä angularin versiosta 1.3 lähtien.

Linkki committiin:
https://github.com/angular/angular.js/commit/3a75b1124d062f64093a90b26630938558909e8d

**Comment by Kaltsoon** [comment]
Jeps, poistan tuon ohjeen materiaalista. Kiitos ilmoituksesta!
