### ISSUE TITLE
TweetTweet-tehtävää ei pysty testaamaan

### ISSUE THREAD

**Issue by JaniL** [web-selainohjelmointi/web-selainohjelmointi.github.io#7]
Tehtävänkuvauksessa pyydetään käyttämään testaukseen Twitterin REST API v1:stä, joka ei ole enää käytössä.

```
/**/tweet.data.parse({"errors":[{"message":"The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.","code":64}]});
```

Nykyisessä rajapinnassa pitää kirjautua OAuthilla.

**Comment by avihavai** [comment]
Tämä ok -- siirryttiin icndb -apin käyttöön.
